const Constants = {
    NAME_MIN_LENGTH: 3,
    NAME_MAX_LENGTH: 20,
    EMAIL_MIN_LENGTH: 5,
    EMAIL_MAX_LENGTH: 255,
    USERNAME_MIN_LENGTH: 5,
    USERNAME_MAX_LENGTH: 255,
    PASSWORD_MIN_LENGTH: 5,
    PASSWORD_MAX_LENGTH: 1024,
    AGE_MIN_VALUE: 6,
    AGE_MAX_VALUE: 100,
    HEIGHT_MIN_VALUE: 40,
    HEIGHT_MAX_VALUE: 300,
    WEIGHT_MIN_VALUE: 1,
    WEIGHT_MAX_VALUE: 1000,
    GOAL_MIN_LENGTH: 2,
    GOAL_MAX_LENGTH: 100,
}

module.exports = Constants;